name: Build Extension Zip
on:
  push:
    branches: ['test/extension-zip-action']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: shopware/shopware-cli-action@v3

      - name: Build extension zip
        id: zip
        uses: shopware/build-extension-zip-action@v1
        with:
          path: .
          output-directory: .build

      - uses: actions/upload-artifact@v7
        with:
          name: extension-zip
          path: ${{ steps.zip.outputs.zip }}