name: Shopware Plugin Verification

on:
  pull_request:
    branches: [main, develop]
  push:
    branches:
      - '**'
    tags:
      - "v*.*.*"

jobs:
  verify-plugin:
    name: Verify Shopware Plugin
    runs-on: ubuntu-latest  

    strategy:
      fail-fast: false
      matrix:
        version-selection: ['lowest', 'highest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  
          tools: composer:v2

      - name: Allow Symfony Runtime Plugin
        run: composer config --no-plugins allow-plugins.symfony/runtime true

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Shopware Extension Verifier
        uses: shopware/github-actions/extension-verifier@main
        with:
          action: check
          check-against: ${{ matrix.version-selection }}

      - name: Fail on Verification Errors
        if: failure()
        run: exit 1
